// Handles saving uploaded listing photos as real files under
// public/uploads/<listingId>/, and cleaning them up on edit/delete.
// Photos are expected to already be reasonably small — the admin page
// compresses them in the browser before upload — so no server-side
// image processing (resizing, re-encoding) happens here.

const fs = require('fs');
const path = require('path');

const UPLOADS_ROOT = path.join(__dirname, '..', 'public', 'uploads');
const MAX_IMAGES = 4;

// Listing ids are generated by the server as "v" + 12 hex chars. Anything
// that doesn't match that shape never gets near the filesystem, so a
// crafted id like "../../etc" can't be used to read or delete elsewhere.
const ID_RE = /^v[0-9a-f]{12}$/;

// The only filenames this code ever writes.
const FILENAME_RE = /^image-[1-9][0-9]?\.jpg$/;

function isValidId(id) {
  return typeof id === 'string' && ID_RE.test(id);
}

function listingDir(id) {
  if (!isValidId(id)) throw new Error('invalid_listing_id');
  const dir = path.join(UPLOADS_ROOT, id);
  // Second line of defence: the resolved path must still sit inside
  // public/uploads/ no matter what.
  const resolved = path.resolve(dir);
  if (resolved !== path.join(path.resolve(UPLOADS_ROOT), id)) {
    throw new Error('invalid_listing_id');
  }
  return dir;
}

// JPEG / PNG / WebP / GIF magic bytes. The admin page re-encodes every
// photo to JPEG in the browser before upload, so in normal use everything
// arriving here is already a JPEG — this check is for anything that talks
// to the API directly and tries to smuggle in an .html or .svg payload
// that would then be served from our own origin.
function isSupportedImage(buf) {
  if (!Buffer.isBuffer(buf) || buf.length < 12) return false;
  if (buf[0] === 0xff && buf[1] === 0xd8 && buf[2] === 0xff) return true; // JPEG
  if (buf.slice(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) return true; // PNG
  if (buf.slice(0, 4).toString('ascii') === 'RIFF' && buf.slice(8, 12).toString('ascii') === 'WEBP') return true; // WebP
  const gif = buf.slice(0, 6).toString('ascii');
  if (gif === 'GIF87a' || gif === 'GIF89a') return true; // GIF
  return false;
}

function publicUrl(id, filename) {
  return `/uploads/${id}/${filename}`;
}

// Reads the files currently referenced by `urls` (which must belong to
// this listing) into memory as buffers, in order. Used before wiping a
// listing's folder on edit, so kept photos survive the rewrite.
function readExistingImages(id, urls) {
  const dir = listingDir(id);
  const prefix = `/uploads/${id}/`;
  return urls
    .filter((u) => typeof u === 'string' && u.startsWith(prefix))
    .map((u) => {
      const filename = u.slice(prefix.length);
      // Without this check a request could ask to "keep"
      // /uploads/<id>/../../../etc/passwd, and that file's contents would
      // be copied into the listing folder and served publicly.
      if (!FILENAME_RE.test(filename)) return null;
      const filePath = path.join(dir, filename);
      if (path.dirname(path.resolve(filePath)) !== path.resolve(dir)) return null;
      if (!fs.existsSync(filePath)) return null;
      return fs.readFileSync(filePath);
    })
    .filter(Boolean);
}

function removeListingDir(id) {
  if (!isValidId(id)) return;
  const dir = listingDir(id);
  if (fs.existsSync(dir)) {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

// Writes `buffers` (already-ordered image data) as image-1.jpg,
// image-2.jpg, ... into a freshly (re)created folder for this listing,
// capped at MAX_IMAGES, and returns their public URLs in order.
function writeListingImages(id, buffers) {
  removeListingDir(id);
  const capped = buffers.slice(0, MAX_IMAGES);
  if (capped.length === 0) return [];
  const dir = listingDir(id);
  fs.mkdirSync(dir, { recursive: true });
  return capped.map((buf, i) => {
    const filename = `image-${i + 1}.jpg`;
    fs.writeFileSync(path.join(dir, filename), buf);
    return publicUrl(id, filename);
  });
}

module.exports = {
  MAX_IMAGES,
  UPLOADS_ROOT,
  isValidId,
  isSupportedImage,
  readExistingImages,
  removeListingDir,
  writeListingImages
};
